mod app;
mod blame_view;
mod branch_tree;
mod commit_list;
mod components;
mod diff_view;
mod editor_view;
mod file_tree;
mod graph_view;
mod highlight;
pub(crate) mod i18n;
pub(crate) mod icons;
pub(crate) mod settings;
pub(crate) mod theme;
pub use app::run;
